name: Validate 'setup-singularity'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 1 * * # Runs at 00:00 UTC on the 1st of every month.

jobs:
  setup-versions:
    name: Setup ${{ matrix.sing }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        sing:
          - 3.5.3, # pre-build
          - 3.6.1, # pre-build 
          - 3.6.4, # pre-build
          - 3.7.1, # pre-build
          - 3.8.0, # from source
          - 3.8.3 # pre-build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Singularity
        uses: ./
        with:
          singularity-version: ${{ matrix.sing }}
      - name: Verify singularity
        run: __tests__/verify-sing.sh ${{ matrix.sing }}
        shell: bash
      - name: Run a singularity container
        run: singularity -v run docker://alpine cat /etc/os-release
