name: Validate 'setup-singularity'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 * * *

jobs:
  setup-versions:
    name: Setup ${{ matrix.sing }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        sing: [3.6.1, 3.5.3]
    steps:
      - uses: actions/checkout@v2
      - name: OS deps
      # Required for sing<3.6
        run: sudo apt install uuid-dev
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - name: Setup Singularity
        uses: ./
        with:
          singularity-version: ${{ matrix.sing }}
      - name: Verify singularity
        run: __tests__/verify-sing.sh ${{ matrix.sing }}
        shell: bash
      - name: Run a singularity container
        run: singularity run docker://alpine cat /etc/os-release
